name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files in public directory
        run: |
          echo "Files in public directory:"
          ls -la public/
          echo ""
          echo "Checking external-website-demo.html:"
          if [ -f public/external-website-demo.html ]; then
            echo "✅ external-website-demo.html exists"
            ls -lh public/external-website-demo.html
          else
            echo "❌ external-website-demo.html NOT FOUND"
          fi
          echo ""
          echo "All HTML files:"
          find public -name "*.html" -type f

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4